apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: n3s4n4j9x-nodejs 
  janus-idp.io/tekton: n3s4n4j9x-nodejs
  backstage.io/kubernetes-id: n3s4n4j9x-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: n3s4n4j9x-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml