apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: n3s4n4j9x-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: n3s4n4j9x-nodejs 
  name: n3s4n4j9x-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: n3s4n4j9x-nodejs 
